#!/usr/bin/env bash
#Install nginx web server
#edit html file to display Hello World!
if ! nginx -v; then
sudo apt-get update -y
sudo apt-get install -y nginx
fi

echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start
