#!/usr/bin/env bash
#Enable redirection to 301 Moved Permanently

apt-get update
apt-get install -y nginx


echo "Hello World!" | sudo tee /var/www/html/index.html
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
replacement="server_name _;\n\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sed -i "s#server_name _;#$replacement#" /etc/nginx/sites-available/default

ufw allow 'NGINX HTTP'
service nginx restart