#!/usr/bin/env bash
#Create custom 404 error page

sudo apt-get update
sudo apt-get install -y nginx

sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html
sudo echo "Hello World!" > /etc/nginx/html/index.html

sudo touch /etc/nginx/html/404.html
sudo echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

sudo cat <<EOL > /etc/nginx/sites-available/default
server {
    listen 80;
    listen [::]:80 default_server;
    root /etc/nginx/html;
    index index.html index.htm;

    location /redirect_me {/watch?v=QH2-TGUlwu4
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
EOL

sudo service nginx restart
