#!/usr/bin/env bash
# Installs Nginx and setting up custom headers

apt-get -y update
apt-get -y install nginx

sudo sed -i "29i \\\tadd_header X-Served-By $HOSTNAME;\n" /etc/nginx/sites-available/default
service nginx restart
