#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get update -y
sudo apt-get install -y haproxy

load_balancer="\nfrontend localnodes\n
\tbind *:80
\tmode http
\tdefault_backend nodes

backend nodes\n
\tbalance roundrobin
\tserver 112572-web-02 54.236.12.78:80 check
\tserver 112572-lb-01 34.232.77.152:80 check
"
echo -e "ENABLED=1\n" | sudo tee -a /etc/default/haproxy
echo -e "$load_balancer" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
